In [7]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Performing some operations
mean = np.mean(arr)
print("Mean:", mean)

# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print("Element at row 2, column 3:", matrix[1, 2])


Mean: 3.0
Element at row 2, column 3: 6


In [2]:
import numpy as np

# Get matrix size from user
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Initialize matrices
matrix1 = np.zeros((rows, cols))
matrix2 = np.zeros((rows, cols))

# Input values for matrix1
print("Enter values for matrix1:")
for i in range(rows):
    for j in range(cols):
        matrix1[i][j] = float(input(f"Matrix1[{i}][{j}]: "))

# Input values for matrix2
print("Enter values for matrix2:")
for i in range(rows):
    for j in range(cols):
        matrix2[i][j] = float(input(f"Matrix2[{i}][{j}]: "))

# Perform operations
addition = matrix1 + matrix2
subtraction = matrix1 - matrix2
# Avoid division by zero
matrix2_non_zero = np.where(matrix2 == 0, 1, matrix2)
division = matrix1 / matrix2_non_zero
multiplication = np.dot(matrix1, matrix2)

# Print results
print("\nMatrix Addition:")
print(addition)
print("\nMatrix Subtraction:")
print(subtraction)
print("\nMatrix Division:")
print(division)
print("\nMatrix Multiplication:")
print(multiplication)


Enter the number of rows: 2
Enter the number of columns: 2
Enter values for matrix1:
Matrix1[0][0]: 3
Matrix1[0][1]: 4
Matrix1[1][0]: 5
Matrix1[1][1]: 6
Enter values for matrix2:
Matrix2[0][0]: 1
Matrix2[0][1]: 2
Matrix2[1][0]: 7
Matrix2[1][1]: 9

Matrix Addition:
[[ 4.  6.]
 [12. 15.]]

Matrix Subtraction:
[[ 2.  2.]
 [-2. -3.]]

Matrix Division:
[[3.         2.        ]
 [0.71428571 0.66666667]]

Matrix Multiplication:
[[31. 42.]
 [47. 64.]]


In [8]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose of the matrix
transpose_matrix = np.transpose(matrix)
print("Transpose Matrix:")
print(transpose_matrix)

# Inverse of the matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Inverse Matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("The matrix is singular, and its inverse does not exist.")

# Identity matrix
identity_matrix = np.identity(3)  # 3x3 identity matrix
print("Identity Matrix:")
print(identity_matrix)


Transpose Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
The matrix is singular, and its inverse does not exist.
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
from PIL import Image
import numpy as np

# Open an image file
image_path = '/content/a.png'  # Replace with the actual path to your image
image = Image.open(image_path)

# Convert image to NumPy array
image_array = np.array(image)

# Get the size of the image (height and width)
image_size = image_array.shape
height, width, channels = image_size

print("Image Size:")
print(f"Height: {height} pixels")
print(f"Width: {width} pixels")
print(f"Channels: {channels} channels")

# Display the image size
image.show()  # Opens the default image viewer to display the image



Image Size:
Height: 494 pixels
Width: 346 pixels
Channels: 4 channels


In [11]:
from PIL import Image
import numpy as np

def compress_svd(image_path, num_components):
    # Load the image and convert to grayscale
    image = Image.open(image_path).convert('L')
    image_array = np.array(image)

    # Perform SVD on the image
    U, S, Vt = np.linalg.svd(image_array, full_matrices=False)

    # Keep only the desired number of singular values/components
    U = U[:, :num_components]
    S = np.diag(S[:num_components])
    Vt = Vt[:num_components, :]

    # Reconstruct the compressed image
    compressed_image_array = np.dot(U, np.dot(S, Vt))

    # Convert back to image
    compressed_image = Image.fromarray(compressed_image_array.astype('uint8'))

    return compressed_image

# Path to the input image
input_image_path = '/content/a.png'  # Replace with the actual path

# Number of components (singular values) to keep for compression
num_components = 50  # Adjust this value to control compression quality

# Compress the image
compressed_image = compress_svd(input_image_path, num_components)

# Save the compressed image
compressed_image.save('compressed_image.jpg')

# Display the original and compressed images
Image.open(input_image_path).show()
compressed_image.show()


In [12]:
from PIL import Image
import numpy as np

def recover_image(image_path, num_components):
    # Load the image and convert to grayscale
    image = Image.open(image_path).convert('L')
    image_array = np.array(image)

    # Perform SVD on the image
    U, S, Vt = np.linalg.svd(image_array, full_matrices=False)

    # Keep only the desired number of singular values/components
    U = U[:, :num_components]
    S = np.diag(S[:num_components])
    Vt = Vt[:num_components, :]

    # Reconstruct the compressed image
    recovered_image_array = np.dot(U, np.dot(S, Vt))

    # Clip values to the valid range [0, 255]
    recovered_image_array = np.clip(recovered_image_array, 0, 255)

    # Convert back to image
    recovered_image = Image.fromarray(recovered_image_array.astype('uint8'))

    return recovered_image

# Path to the input image
input_image_path = '/content/compressed_image.jpg'  # Replace with the actual path

# Number of components (singular values) to keep for recovery
num_components = 50  # Adjust this value to control recovery quality

# Recover the image
recovered_image = recover_image(input_image_path, num_components)

# Save the recovered image
recovered_image.save('recovered_image.jpg')

# Display the original and recovered images
Image.open(input_image_path).show()
recovered_image.show()


In [13]:
import numpy as np

# Create a sample matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Perform full SVD
U, S, Vt = np.linalg.svd(A, full_matrices=True)

print("Matrix U:")
print(U)
print("Diagonal matrix Σ:")
print(S)
print("Matrix V^T:")
print(Vt)


Matrix U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Diagonal matrix Σ:
[9.52551809 0.51430058]
Matrix V^T:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [14]:
import numpy as np

# Create a sample matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Perform truncated SVD
k = 1  # Number of singular values to keep
U, S, Vt = np.linalg.svd(A, full_matrices=False)
Uk = U[:, :k]
Sk = np.diag(S[:k])
Vtk = Vt[:k, :]

# Reconstruct the matrix
A_approx = np.dot(Uk, np.dot(Sk, Vtk))

print("Original Matrix:")
print(A)
print("Approximated Matrix:")
print(A_approx)


Original Matrix:
[[1 2]
 [3 4]
 [5 6]]
Approximated Matrix:
[[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


In [15]:
import numpy as np

# Create a sample matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Perform economy SVD
k = 1  # Number of singular values to keep
U, S, _ = np.linalg.svd(A, full_matrices=False)

# Keep only the first k columns of U and the first k singular values of S
Uk = U[:, :k]
Sk = np.diag(S[:k])

# Reconstruct the matrix
A_approx = np.dot(Uk, Sk)

print("Original Matrix:")
print(A)
print("Approximated Matrix:")
print(A_approx)


Original Matrix:
[[1 2]
 [3 4]
 [5 6]]
Approximated Matrix:
[[-2.18941839]
 [-4.99846626]
 [-7.80751414]]
